name = "Prominence II ES - Tomodachi"
author = "Agustin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a622880ba9c47c68291f8662c97eacf7a6921f045507ca7a13489d7acc8bb058"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
