name = "Prominence II ES - Tomodachi"
author = "Agustin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db2a8e677761d4bb91ddabae0c86ed7a0b6ac751dfeb9f2d217e7904231e5f33"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
