name = "Prominence II ES - Tomodachi"
author = "Agustin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfb9bcb393b2502f5196b08678d1582f0fe0490f60c15ce9b6b48b82540814ec"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
